#2432 Rationalisation of web tests configuration
1. Relocate `Start` classes for the test app to test sources.

   This change resolves an issue with the tg-serialiser web test that
   required a workaround for the test to succeed.
   This test involved `FactoryForTestingEntities`, which depends on `junit`.
   `Start` being in main sources, `junit` was not available on the
   classpath, causing a `NoClassDefFoundError`.

2. Localise the scope of `/test/...` HTTP endpoints.

   This change makes them applicable only to the test app.
   Previously, they were being registered in the base configuration,
   leaking into TG applications.